[package]
name = "lily_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
chumsky = "0.8.0"
dbg-pls = {version = "0.3.3", features = ["colors", "derive", "pretty", "dbg-pls-derive"]}
nom = "7.1.1"
